"""The 41 CUAD clause categories, named as in the clause dataset, each with a one-line description
condensed from the CUAD v1 datasheet."""

CATEGORIES: dict[str, str] = {
    "Document Name": "the name of the contract",
    "Parties": "the two or more parties who signed the contract",
    "Agreement Date": "the date of the contract",
    "Effective Date": "the date when the contract becomes effective",
    "Expiration Date": "the date the contract's initial term expires",
    "Renewal Term": "the renewal term after the initial term, including automatic or unilateral extensions",
    "Notice Period To Terminate Renewal": "the notice period required to terminate a renewal",
    "Governing Law": "which state's or country's law governs the contract",
    "Most Favored Nation": "better terms granted to a third party must be extended to the buyer",
    "Non-Compete": "a restriction on competing with the counterparty or operating in a geography, business or technology",
    "Exclusivity": "an exclusive dealing commitment, such as buying all requirements from one party or not licensing or selling to third parties",
    "No-Solicit Of Customers": "a restriction on contracting with or soliciting the counterparty's customers or partners",
    "Competitive Restriction Exception": "an exception or carve-out to a non-compete, exclusivity or no-solicit restriction",
    "No-Solicit Of Employees": "a restriction on soliciting or hiring the counterparty's employees or contractors",
    "Non-Disparagement": "a requirement not to disparage the counterparty",
    "Termination For Convenience": "a party may terminate without cause by giving notice and waiting out a period",
    "Rofr/Rofo/Rofn": "a right of first refusal, first offer or first negotiation over equity, technology, assets, products or services",
    "Change Of Control": "termination, consent or notice rights if a party undergoes a change of control such as a merger or sale",
    "Anti-Assignment": "consent or notice is required before the contract is assigned to a third party",
    "Revenue/Profit Sharing": "a party must share revenue or profit with the counterparty",
    "Price Restrictions": "a restriction on a party's ability to raise or reduce prices",
    "Minimum Commitment": "a minimum order size or minimum amount per period that a party must buy",
    "Volume Restriction": "a fee increase or consent requirement if usage of the product or service exceeds a threshold",
    "Ip Ownership Assignment": "intellectual property created by one party becomes the counterparty's property",
    "Joint Ip Ownership": "joint or shared ownership of intellectual property between the parties",
    "License Grant": "a license granted by one party to its counterparty",
    "Non-Transferable License": "a limit on transferring the granted license to a third party",
    "Affiliate License-Licensor": "a license grant by, or covering the intellectual property of, the licensor's affiliates",
    "Affiliate License-Licensee": "a license grant that extends to the licensee's affiliates",
    "Unlimited/All-You-Can-Eat-License": "an enterprise, all-you-can-eat or unlimited usage license",
    "Irrevocable Or Perpetual License": "a license grant that is irrevocable or perpetual",
    "Source Code Escrow": "source code deposited in escrow for release to the counterparty on events such as bankruptcy",
    "Post-Termination Services": "obligations that continue after termination or expiration, such as transition, wind-down or last-buy commitments",
    "Audit Rights": "a right to audit the counterparty's books, records or premises for compliance with the contract",
    "Uncapped Liability": "a party's liability is uncapped for a breach, or for a type of breach such as infringement or confidentiality",
    "Cap On Liability": "a cap on liability for breach, including a time limit for claims or a maximum recovery",
    "Liquidated Damages": "liquidated damages for breach, or a fee payable on termination",
    "Warranty Duration": "the duration of a warranty against defects in technology, products or services",
    "Insurance": "insurance that one party must maintain for the counterparty's benefit",
    "Covenant Not To Sue": "a party may not contest the counterparty's intellectual property or bring unrelated claims against it",
    "Third Party Beneficiary": "a non-party who benefits from the contract and can enforce it against a party",
}
